[project]
name = "lambda-imitation"
version = "0.0.1"
dependencies = [
  "numpy",
  "gymnasium",
]
requires-python = ">=3.12"
authors = [
  {name = "Tobias Kietreiber", email = "tobias.kietreiber@fhstp.ac.at"},
]
maintainers = [
  {name = "Tobias Kietreiber", email = "tobias.kietreiber@fhstp.ac.at"}
]
description = "Repository for the ICRA submission on offline imitation learning using lambda discrepancies"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICEN[CS]E.*"]
keywords = ["lambda discrepancy", "offline imitation learning", "ICRA 2026"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
